// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: ledger.proto

package ledgerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Reconciliation_GetSagaStatus_FullMethodName = "/secureledger.v1.Reconciliation/GetSagaStatus"
)

// ReconciliationClient is the client API for Reconciliation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReconciliationClient interface {
	GetSagaStatus(ctx context.Context, in *GetSagaStatusRequest, opts ...grpc.CallOption) (*GetSagaStatusResponse, error)
}

type reconciliationClient struct {
	cc grpc.ClientConnInterface
}

func NewReconciliationClient(cc grpc.ClientConnInterface) ReconciliationClient {
	return &reconciliationClient{cc}
}

func (c *reconciliationClient) GetSagaStatus(ctx context.Context, in *GetSagaStatusRequest, opts ...grpc.CallOption) (*GetSagaStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSagaStatusResponse)
	err := c.cc.Invoke(ctx, Reconciliation_GetSagaStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReconciliationServer is the server API for Reconciliation service.
// All implementations must embed UnimplementedReconciliationServer
// for forward compatibility.
type ReconciliationServer interface {
	GetSagaStatus(context.Context, *GetSagaStatusRequest) (*GetSagaStatusResponse, error)
	mustEmbedUnimplementedReconciliationServer()
}

// UnimplementedReconciliationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReconciliationServer struct{}

func (UnimplementedReconciliationServer) GetSagaStatus(context.Context, *GetSagaStatusRequest) (*GetSagaStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSagaStatus not implemented")
}
func (UnimplementedReconciliationServer) mustEmbedUnimplementedReconciliationServer() {}
func (UnimplementedReconciliationServer) testEmbeddedByValue()                        {}

// UnsafeReconciliationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReconciliationServer will
// result in compilation errors.
type UnsafeReconciliationServer interface {
	mustEmbedUnimplementedReconciliationServer()
}

func RegisterReconciliationServer(s grpc.ServiceRegistrar, srv ReconciliationServer) {
	// If the following call pancis, it indicates UnimplementedReconciliationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Reconciliation_ServiceDesc, srv)
}

func _Reconciliation_GetSagaStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSagaStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReconciliationServer).GetSagaStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reconciliation_GetSagaStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReconciliationServer).GetSagaStatus(ctx, req.(*GetSagaStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Reconciliation_ServiceDesc is the grpc.ServiceDesc for Reconciliation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Reconciliation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "secureledger.v1.Reconciliation",
	HandlerType: (*ReconciliationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSagaStatus",
			Handler:    _Reconciliation_GetSagaStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ledger.proto",
}
